# Generated by Django 6.0.5 on 2026-05-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('type', models.CharField(choices=[('monetary', 'Monétaire'), ('labor', 'Échange de travail'), ('mutual_writeoff', 'Annulation mutuelle')], max_length=20, verbose_name='Type')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('virement', 'Virement')], max_length=20, verbose_name='Méthode (si monétaire)')),
                ('description', models.TextField(verbose_name='Description')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('disputed', 'Contesté')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par')),
                ('farm_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_as_a', to='farms.farm', verbose_name='Ferme A (proposante)')),
                ('farm_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_as_b', to='farms.farm', verbose_name='Ferme B (contrepartie)')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_proposed', to=settings.AUTH_USER_MODEL, verbose_name='Proposé par')),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TabEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (positif = crédit, négatif = débit)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde global après')),
                ('entry_type', models.CharField(choices=[('order', 'Commande'), ('settlement', 'Règlement'), ('adjustment', 'Ajustement')], max_length=20, verbose_name="Type d'entrée")),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tab_entries', to='farms.farm', verbose_name='Ferme')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tab_entries', to='market.order', verbose_name='Commande')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tab_entries', to='billing.settlement', verbose_name='Règlement')),
            ],
            options={
                'verbose_name': 'Entrée de compte',
                'verbose_name_plural': 'Entrées de compte',
                'ordering': ['-created_at'],
            },
        ),
    ]
