# Generated by Django 6.0.5 on 2026-05-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Début (lundi)')),
                ('end_date', models.DateField(verbose_name='Fin (dimanche)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Semaine active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Semaine',
                'verbose_name_plural': 'Semaines',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité disponible')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('litre', 'litre'), ('bouquet', 'bouquet'), ('botte', 'botte'), ('pièce', 'pièce')], max_length=20, verbose_name='Unité')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Prix à l'unité (€)")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='farms.farm', verbose_name='Ferme')),
                ('farm_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='farms.farmproduct', verbose_name='Produit')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='market.week', verbose_name='Semaine')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('confirmed', 'Confirmée'), ('declined', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('buyer_notes', models.TextField(blank=True, verbose_name="Notes de l'acheteur")),
                ('seller_notes', models.TextField(blank=True, verbose_name='Notes du vendeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer', to='farms.farm', verbose_name='Ferme acheteuse')),
                ('seller_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_seller', to='farms.farm', verbose_name='Ferme vendeuse')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire (€)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='market.listing', verbose_name='Annonce')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='WantedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity_wanted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité souhaitée')),
                ('unit', models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('litre', 'litre'), ('bouquet', 'bouquet'), ('botte', 'botte'), ('pièce', 'pièce')], max_length=20, verbose_name='Unité')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Satisfaite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_listings', to='farms.cropcategory', verbose_name='Catégorie')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_listings', to='farms.farm', verbose_name='Ferme')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wanted_listings', to='market.week', verbose_name='Semaine')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WantedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_offered', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité proposée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responding_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_responses', to='farms.farm', verbose_name='Ferme répondante')),
                ('wanted_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='market.wantedlisting', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Réponse à une demande',
                'verbose_name_plural': 'Réponses aux demandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
