# Generated by Django 6.0.5 on 2026-05-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('farm', 'farm_product', 'week'), name='unique_listing_per_farm_product_week'),
        ),
    ]
